SYMLINK := ln -sf
CP := cp

.PHONY: install
install:
	$(SYMLINK) $(CURDIR)/CLAUDE.md $(HOME)/.claude/CLAUDE.md
	$(SYMLINK) $(CURDIR)/settings.json $(HOME)/.claude/settings.json
	$(SYMLINK) $(CURDIR)/statusline.sh $(HOME)/.claude/statusline.sh
