SYMLINK := ln -sf
CP := cp

.PHONY: install
install:
	$(SYMLINK) CLAUDE.md $(HOME)/.claude/CLAUDE.md
	$(SYMLINK) settings.json $(HOME)/.claude/settings.json
	$(SYMLINK) statusline.sh $(HOME)/.claude/statusline.sh
