call plug#begin()
call plug#end()

set number
set relativenumber
set cursorline
set noswapfile
set nobackup
set noundofile
set expandtab
set tabstop=4
set shiftwidth=4
language messages C

syntax enable

set statusline=\ %f\ %y%r%=%l,%c%V\ %m
set laststatus=2

" Go
au FileType go setlocal noet

" Makefile
au FileType make setlocal noet
