" Plug-ins
call plug#begin()
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'bluz71/vim-moonfly-colors'
call plug#end()

set number
set cursorline
set noswapfile
set nobackup
set noundofile
set termguicolors
set expandtab
set tabstop=4
set shiftwidth=4
set signcolumn=yes
language messages C

syntax enable
colorscheme moonfly

set statusline=\ %f\ %y%r%=%l,%c%V\ %m
set laststatus=2

" Go
autocmd FileType go setlocal noexpandtab

" Makefile
autocmd FileType make setlocal noexpandtab
