" Plug-ins
cal plug#begin()
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'bluz71/vim-moonfly-colors'
cal plug#end()

se nu
se cul
se noswf
se nobk
se noudf
se tgc
se et
se ts=4
se sw=4
se scl=yes
lan messages C

syntax enable
colo moonfly

se stl=\ %f\ %y%r%=%l,%c%V\ %m
se ls=2

" Go
au FileType go setl noet

" Makefile
au FileType make setl noet
